//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentManager.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_lt_LT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_lt_LT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TournamentManager.Locales.Resource.lt-LT", typeof(Resource_lt_LT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baigtas.
        /// </summary>
        internal static string ActivityStatus_Ended {
            get {
                return ResourceManager.GetString("ActivityStatus_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiesiogiai.
        /// </summary>
        internal static string ActivityStatus_Live {
            get {
                return ResourceManager.GetString("ActivityStatus_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ateinantis.
        /// </summary>
        internal static string ActivityStatus_Upcoming {
            get {
                return ResourceManager.GetString("ActivityStatus_Upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuotrauka.
        /// </summary>
        internal static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimimo data.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dvigubas Iškritimas.
        /// </summary>
        internal static string BracketType_DE {
            get {
                return ResourceManager.GetString("BracketType_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viengubas Iškritimas.
        /// </summary>
        internal static string BracketType_SE {
            get {
                return ResourceManager.GetString("BracketType_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atšaukti.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pateikti.
        /// </summary>
        internal static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populiaru.
        /// </summary>
        internal static string Featured {
            get {
                return ResourceManager.GetString("Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rungtynės.
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tautybė.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagrindinis.
        /// </summary>
        internal static string NavLink_Home {
            get {
                return ResourceManager.GetString("NavLink_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisijungti.
        /// </summary>
        internal static string NavLink_Login {
            get {
                return ResourceManager.GetString("NavLink_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atsijungti.
        /// </summary>
        internal static string NavLink_Logout {
            get {
                return ResourceManager.GetString("NavLink_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žaidėjai.
        /// </summary>
        internal static string NavLink_Players {
            get {
                return ResourceManager.GetString("NavLink_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registruotis.
        /// </summary>
        internal static string NavLink_Register {
            get {
                return ResourceManager.GetString("NavLink_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komandos.
        /// </summary>
        internal static string NavLink_Teams {
            get {
                return ResourceManager.GetString("NavLink_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnyrai.
        /// </summary>
        internal static string NavLink_Tournaments {
            get {
                return ResourceManager.GetString("NavLink_Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slapyvardis.
        /// </summary>
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ieškokite slapyvardžio....
        /// </summary>
        internal static string Nickname_Search {
            get {
                return ResourceManager.GetString("Nickname_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusas.
        /// </summary>
        internal static string Player_Status {
            get {
                return ResourceManager.GetString("Player_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktyvus.
        /// </summary>
        internal static string PlayerStatus_Active {
            get {
                return ResourceManager.GetString("PlayerStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atsarginis.
        /// </summary>
        internal static string PlayerStatus_Benched {
            get {
                return ResourceManager.GetString("PlayerStatus_Benched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasitraukęs.
        /// </summary>
        internal static string PlayerStatus_Retired {
            get {
                return ResourceManager.GetString("PlayerStatus_Retired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reitingas.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europa.
        /// </summary>
        internal static string Region_EU {
            get {
                return ResourceManager.GetString("Region_EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šiaurės Amerika.
        /// </summary>
        internal static string Region_NA {
            get {
                return ResourceManager.GetString("Region_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pavadinimas.
        /// </summary>
        internal static string Team_Name {
            get {
                return ResourceManager.GetString("Team_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taškai.
        /// </summary>
        internal static string Team_Points {
            get {
                return ResourceManager.GetString("Team_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reitingas.
        /// </summary>
        internal static string Team_Ranking {
            get {
                return ResourceManager.GetString("Team_Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regionas.
        /// </summary>
        internal static string Team_Region {
            get {
                return ResourceManager.GetString("Team_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnyrai.
        /// </summary>
        internal static string Tournaments {
            get {
                return ResourceManager.GetString("Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artimiausi turnyrai.
        /// </summary>
        internal static string Upcoming_Tournaments {
            get {
                return ResourceManager.GetString("Upcoming_Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sveiki!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
